version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database:/db_data
    networks:
      - postgres_network

  webapp:
    container_name: webapp_container
    restart: always
    depends_on:
      - postgres
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - postgres_network
      - nginx_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
      - nginx_network

  nginx:
    image: nginx:1.23.3
    container_name: nginx_container
    depends_on:
      - pgadmin
      - webapp
    volumes:
      - ./nginx/my_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./README.md:/static/documentation/README.md
      - ./img/:/static/documentation/img/
      - ./static:/static
    ports:
      - "8081:8080"
    networks:
      - nginx_network

volumes:
  postgres:
  pgadmin-data:

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge