// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Driver struct {
	ID        int    `json:"ID"`
	Name      string `json:"Name"`
	Country   string `json:"Country"`
	BirthDate string `json:"BirthDate"`
}

type DriverInput struct {
	ID        int    `json:"ID"`
	Name      string `json:"Name"`
	Country   string `json:"Country"`
	BirthDate string `json:"BirthDate"`
}

type GrandPrix struct {
	ID      int    `json:"ID"`
	Season  int    `json:"Season"`
	Name    string `json:"Name"`
	DateNum int    `json:"DateNum"`
	Month   string `json:"Month"`
	Place   string `json:"Place"`
	TrackID int    `json:"TrackId"`
}

type GrandPrixInput struct {
	ID      int    `json:"ID"`
	Season  int    `json:"Season"`
	Name    string `json:"Name"`
	DateNum int    `json:"DateNum"`
	Month   string `json:"Month"`
	Place   string `json:"Place"`
	TrackID int    `json:"TrackId"`
}

type QualResult struct {
	ID          int    `json:"ID"`
	DriverPlace int    `json:"DriverPlace"`
	DriverID    int    `json:"DriverId"`
	TeamID      int    `json:"TeamId"`
	Q1time      string `json:"Q1time"`
	Q2time      string `json:"Q2time"`
	Q3time      string `json:"Q3time"`
	GPId        int    `json:"GPId"`
}

type QualResultInput struct {
	ID          int    `json:"ID"`
	DriverPlace int    `json:"DriverPlace"`
	DriverID    int    `json:"DriverId"`
	TeamID      int    `json:"TeamId"`
	Q1time      string `json:"Q1time"`
	Q2time      string `json:"Q2time"`
	Q3time      string `json:"Q3time"`
	GPId        int    `json:"GPId"`
}

type QualResultView struct {
	ID          int    `json:"ID"`
	DriverPlace int    `json:"DriverPlace"`
	DriverName  string `json:"DriverName"`
	TeamName    string `json:"TeamName"`
	Q1time      string `json:"Q1time"`
	Q2time      string `json:"Q2time"`
	Q3time      string `json:"Q3time"`
	GPName      string `json:"GPName"`
}

type RaceResult struct {
	ID          int `json:"ID"`
	DriverPlace int `json:"DriverPlace"`
	DriverID    int `json:"DriverId"`
	TeamID      int `json:"TeamId"`
	GPId        int `json:"GPId"`
}

type RaceResultInput struct {
	ID          int `json:"ID"`
	DriverPlace int `json:"DriverPlace"`
	DriverID    int `json:"DriverId"`
	TeamID      int `json:"TeamId"`
	GPId        int `json:"GPId"`
}

type RaceResultView struct {
	ID          int    `json:"ID"`
	DriverPlace int    `json:"DriverPlace"`
	DriverName  string `json:"DriverName"`
	TeamName    string `json:"TeamName"`
	GPName      string `json:"GPName"`
}

type Standings struct {
	ID         int    `json:"ID"`
	Season     int    `json:"Season"`
	DriverName string `json:"DriverName"`
	TeamName   string `json:"TeamName"`
	Score      int    `json:"Score"`
}

type StandingsInput struct {
	ID         int    `json:"ID"`
	Season     int    `json:"Season"`
	DriverName string `json:"DriverName"`
	TeamName   string `json:"TeamName"`
	Score      int    `json:"Score"`
}

type Team struct {
	ID      int    `json:"ID"`
	Name    string `json:"Name"`
	Country string `json:"Country"`
	Base    string `json:"Base"`
}

type TeamInput struct {
	ID      int    `json:"ID"`
	Name    string `json:"Name"`
	Country string `json:"Country"`
	Base    string `json:"Base"`
}

type Track struct {
	ID      int    `json:"ID"`
	Name    string `json:"Name"`
	Country string `json:"Country"`
	Town    string `json:"Town"`
}

type TrackInput struct {
	ID      int    `json:"ID"`
	Name    string `json:"Name"`
	Country string `json:"Country"`
	Town    string `json:"Town"`
}

type User struct {
	ID       int    `json:"ID"`
	Login    string `json:"Login"`
	Password string `json:"Password"`
	Role     string `json:"Role"`
}

type UserInput struct {
	Login    string `json:"Login"`
	Password string `json:"Password"`
	Role     string `json:"Role"`
}

type UserLogIn struct {
	Login    string `json:"Login"`
	Password string `json:"Password"`
}
